---
title: "Introduction"
output: html_document
---

Dans le cadre de cours, nous, étudiants de M1 Statistiques et Science des Données, avons réalisé un projet sur les résultats de la Formule 1. Le choix de la Formule 1 s'est porté sur le fait que l'on est tous intéressé par ce domaine et qu'il y a assez de données pour les exploiter sous différentes approches et graphiques intéractifs. On a voulu simplifier la visualisation des données avec des graphiques sur une ou plusieurs années plutôt que des tableaux qui se trouve sur plusieurs pages web et donc difficile à visualiser. La communication entre les membres du groupe hors présentiel s'est faite sur Discord. Ce projet est en language R et sa finalité est une interface Shiny. Le projet a été divisé en 4 grandes parties, le web-scraping pour récupérer nos tableaux de données, la création des differences fonctions pour afficher les graphiques interactifs, la création d'un package qui regroupe nos fonctions et données et enfin le développement de l'interface Shiny. Ce rapport est divisé en 3 principales parties, la gestion du projet puis sa réalisation et enfin son évaluation générale.