---
title: "Web Scraping"
output: html_document
---
<br>



<br/>
Le web scraping consiste à récolter des données sur des sites web. Pour ce projet sur la formule 1, on a décidé de créer 6 bases de données pour produire des graphiques. On a dans un premier temps récupérer l’année 2020 (cf WebscrapingV3.R) sur le site officiel de la [formule 1](https://www.formula1.com/en/results.html) puis on a développé notre code pour chaque fichier de données de 1950 à 2020 sauf pour les équipes où les classements ont commencé qu’en 1958 (cf WebscrapingV4.R). On a rencontré plusieurs problèmes quand on a récupéré les données notamment les noms qui comportaient des backslash n et des espaces et caractères inutiles et les teams qui avaient des données inutiles dans le vecteur qu’on récupérait.
<br>



<br/>
Avec dataDriversParRaces on a eu un plus gros problème pour la création des adresses url des pilotes. Une partie de l’url est créée à partir du nom du pilote, seulement certains noms étaient particuliers et donc demander une réécriture manuelle de cette partie du l’url.
<br>



<br/>
Pour dataStartingGrid on a rencontré un autre problème du web scraping. L’url utilisée est de ce type : <span style="color:blue">htt</span><span style="color:blue">ps://www.formula1.com/en/results.html/</span> année <span style="color:blue">/races/</span> numéro unique associé à un grand prix <span style="color:blue">/</span> nom du grand prix <span style="color:blue">/starting-grid.html</span>. Le problème vient que le numéro unique attribué à chaque grand prix n’a pas d’ordre logique.
<br>



<br/>
Pour certains graphiques on utilise les données de ces 2 bases de données, on s’est rendu compte que pour certaines années on s’attendait à avoir le même nombre de lignes entre ces 2 bases de données comme l’un à les données de tous les pilotes sur chaque grand prix à l’arrivée et l’autre les données de chaque grand prix des pilotes au départ mais on n’avait pas ça. Cela vient du fait que là où on récupère le nom des pilotes, on a que les pilotes qui ont eu au moins 1 point dans l’année et pour les autres il n’y a pas de lien pour récupérer ces données. De ce problème on a identifié un problème dans dataDrivers qui du coup ne contenait pas tous les pilotes par année. On a donc décidé de changer de lien pour récupérer les données. Au lieu de faire pilote par pilote par année, on récolte les données grand prix par grand prix par année. La taille des données est une nouvelle fois différente, cette fois ci le problème vient du fait que certaines voitures sont copilotées et qu’il y a un pilote au départ et 2 à l’arrivée par exemple. Un autre problème qui aurait pu être identifié avant est que la starting grid où l’on récupère les données de dataStartingGrid n’est pas présente pour tous les grands prix entre 1950 et 1959 donc on avait pour certains grands prix des données fausses. On a donc décidé de changer de site pour créer les 3 bases de données citées.
<br>



<br/>
On a utilisé le site [racing-statistics](https://www.racing-statistics.com/en/seasons) où on a eu aussi des problemes entre les pilotes de départ et d’arrivée. On a donc sélectionné pour les données d’arrivée que celles des pilotes qui sont partis pour avoir les données qu’on voulait. Les pilotes qui étaient à l’arrivée et pas au départ étaient en général des pilotes qui n’avaient pas pris les départs mais qui étaient dans la grille d’arrivée une erreur du site on pense. On obtient donc le fichier WebscrapingVfinale.R qui crée sans erreur et comme on veut les 6 bases de données.
